import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Your Top Tracks and Artists</title>
                <meta name="description" content="App generated by create next app using the Spotify API" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} bg-white flex flex-col justify-evenly items-center p-10 lg:flex-row`}>
                <div className="py-16">
                    <div className="relative mx-auto max-w-7xl text-center sm:text-left">
                        <div className="sm:max-w-lg">
                            <h1 className="font text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Music Profile for Spotify!</h1>
                            <p className="mt-8 text-xl text-gray-500">Easily keep track of your Spotify listening habits, including your most-played artists, top tracks, and favorite playlists.</p>
                        </div>
                        <div className="mt-10">
                            <Link className={inter.className} href={`/profile`}>
                                <button className="inline-block rounded-full border border-transparent bg-indigo-600 px-8 py-3 text-center font-medium text-white hover:bg-indigo-700">
                                    Go to Music Profile
                                </button>
                            </Link>
                        </div>
                    </div>
                </div>
                {/* Decorative image grid */}
                <div className="grid grid-cols-2 xl:grid-cols-3">
                    <span className="circle">
                        <img src="/images/ariana.png" alt="" />
                    </span>
                    <span className="circle">
                        <img src="/images/blackpink.png" alt="" />
                    </span>
                    <span className="circle">
                        <img src="/images/weeknd.png" alt="" />
                    </span>
                    <span className="circle">
                        <img src="/images/taylorswift.png" alt="" />
                    </span>
                    <span className="circle">
                        <img src="/images/zedd.png" alt="" />
                    </span>
                </div>
            </main>
        </>
    );
}
