import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Your Top Tracks and Artists</title>
        <meta name="description" content="App generated by create next app using the Spotify API" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link className={inter.className} href={`/profile`}>
          <button className={styles.button}>Go to Music Profile</button>
        </Link>
      </main>
    </>
  );
}
